EXPECTED_FIELDS = [
    "First Name",
    "Last Name",
    "Date of Birth",
    "Birth City",
    "Birth State",
    "Age",
    "Blood Group",
    "Nationality",
    "Joining Date of first professional role",
    "Designation of first professional role",
    "Salary of first professional role",
    "Salary currency of first professional role",
    "Current Organization",
    "Current Joining Date",
    "Current Designation",
    "Current Salary",
    "Current Salary Currency",
    "Previous Organization",
    "Previous Joining Date",
    "Previous end year",
    "Previous Starting Designation",
    "High School",
    "12th standard pass out year",
    "12th overall board score",
    "Undergraduate degree",
    "Undergraduate college",
    "Undergraduate year",
    "Undergraduate CGPA",
    "Graduation degree",
    "Graduation college",
    "Graduation year",
    "Graduation CGPA",
    "Certifications 1",
    "Certifications 2",
    "Certifications 3",
    "Certifications 4",
    "Technical Proficiency"
]
